const tools = {
    "select": {
        size: 0,
        type: "none",
        color: "#000000",
        resizable: false,
        selectableColor: false,
        cursor: 'move',
        icon: "selectIcon.svg",
    },
    "pencil": {
        size: 5,
        type: "mesh",
        color: "#000000",
        resizable: false,
        selectableColor: false,
        cursor: 'draw',
        icon: "pencilIcon.svg",
    },
    "fill": {
        size: 1,
        type: "fill",
        color: "#000000",
        resizable: false,
        selectableColor: true,
        cursor: 'crosshair',
        icon: "fillIcon.svg",
    },
    "brush": {
        size: 10,
        type: "mesh",
        color: "#000000",
        resizable: true,
        selectableColor: true,
        cursor: 'draw',
        icon: "brushIcon.svg",
    },
    "eraser": {
        size: 10,
        type: "mesh",
        color: "none",
        resizable: true,
        selectableColor: false,
        cursor: 'draw',
        icon: "eraserIcon.svg",
    },
    "line": {
        size: 10,
        type: "line",
        color: "#000000",
        resizable: true,
        selectableColor: true,
        cursor: 'draw',
        icon: "lineIcon.svg",
    },
    "rectangle": {
        size: 1,
        type: "rect",
        color: "#000000",
        resizable: true,
        selectableColor: true,
        cursor: 'draw',
        icon: "rectangleIcon.svg",
    },
    "ellipse": {
        size: 1,
        type: "ellipse",
        color: "#000000",
        resizable: true,
        selectableColor: true,
        cursor: 'draw',
        icon: "ellipseIcon.svg",
    },
    "triangle": {
        size: 1,
        type: "triangle",
        color: "#000000",
        resizable: true,
        selectableColor: true,
        cursor: 'draw',
        icon: "triangleIcon.svg",
    },

};