const tools = {
    "select": {
        size: 0,
        type: "none",
        color: "#000000",
        resizable: false,
        selectableColor: false,
        cursor: 'move',
        icon: "select",
    },
    "pencil": {
        size: 5,
        type: "mesh",
        color: "#000000",
        resizable: false,
        selectableColor: false,
        cursor: 'draw',
        icon: "pencil",
    },
    "fill": {
        size: 1,
        type: "fill",
        color: "#000000",
        resizable: false,
        selectableColor: true,
        cursor: 'crosshair',
        icon: "fill",
    },
    "brush": {
        size: 10,
        type: "mesh",
        color: "#000000",
        resizable: true,
        selectableColor: true,
        cursor: 'draw',
        icon: "brush",
    },
    "eraser": {
        size: 10,
        type: "mesh",
        color: "none",
        resizable: true,
        selectableColor: false,
        cursor: 'draw',
        icon: "eraser",
    },
    "line": {
        size: 10,
        type: "line",
        color: "#000000",
        resizable: true,
        selectableColor: true,
        cursor: 'draw',
        icon: "line",
    },
    "rectangle": {
        size: 1,
        type: "rect",
        color: "#000000",
        resizable: true,
        selectableColor: true,
        cursor: 'draw',
        icon: "rectangle",
    },
    "ellipse": {
        size: 1,
        type: "ellipse",
        color: "#000000",
        resizable: true,
        selectableColor: true,
        cursor: 'draw',
        icon: "ellipse",
    },
    "triangle": {
        size: 1,
        type: "triangle",
        color: "#000000",
        resizable: true,
        selectableColor: true,
        cursor: 'draw',
        icon: "triangle",
    },

};